{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata: 
    name: {{ include "publicdns-detector.fullname" . }}-gateway
    labels:
        {{- include "publicdns-detector.labels" . | nindent 4 }}
    annotations:
      {{- if .Values.gateway.proxyV2 }}
      haproxy.org/send-proxy-v2: 'true'
      {{- end}}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
  - name: dns
    protocol: UDP
    port: {{ .Values.service.dnsPort }}
    allowedRoutes:
      kinds:
      - kind: UDPRoute
      namespaces:
        from: Same
{{- end}}