{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "publicdns-detector.fullname" . }}-ingress
  labels:
    {{- include "publicdns-detector.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ printf "*.%s" .Values.zone | quote }}
      http:
        paths:
        - backend:
            service:
              name: {{ include "publicdns-detector.fullname" . }}-service
              port:
                 number: {{ .Values.service.httpPort }}
          path: /
          pathType: Prefix
  tls:
  - hosts:
    - {{ printf "*.%s" .Values.zone | quote }}
    secretName: {{ .Values.zone }}-tls-secret
{{- end }}