name: Build and Release publicdns-detector

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/publicdns-detector-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o bin/publicdns-detector-linux-arm64
          GOOS=windows GOARCH=amd64 go build -o bin/publicdns-detector-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o bin/publicdns-detector-macos-amd64
          GOOS=darwin GOARCH=arm64 go build -o bin/publicdns-detector-macos-arm64

      - name: Install GitHub CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.0.0/gh_2.0.0_linux_amd64.tar.gz | sudo tar xz -C /usr/local/bin
      
      - name: Upload Release Asset
        id: upload-release-asset-linux
        run: |
          gh release upload ${{ github.ref }} bin/publicdns-detector-linux-amd64 --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload-release-asset-linux-arm64
        run: |
          gh release upload ${{ github.ref }} bin/publicdns-detector-linux-arm64 --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload-release-asset-windows
        run: |
          gh release upload ${{ github.ref }} bin/publicdns-detector-windows-amd64.exe --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload-release-asset-macos-amd64
        run: |
          gh release upload ${{ github.ref }} bin/publicdns-detector-macos-amd64 --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload-release-asset-macos-arm64
        run: |
          gh release upload ${{ github.ref }} bin/publicdns-detector-macos-arm64 --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}